// Environmental variables
const BACKEND_PORT = process.env.REACT_APP_BACKEND_PORT;
const BACKEND_PROTOCOL = process.env.REACT_APP_BACKEND_PROTOCOL;
const BACKEND_HOST = process.env.REACT_APP_BACKEND_HOST;
// const BACKEND_HOST = '192.168.227.20'

// URLS
const AUTH_BASE_URL = `${BACKEND_PROTOCOL}://${BACKEND_HOST}:${BACKEND_PORT}/auth`;
const USER_BASE_URL = `${BACKEND_PROTOCOL}://${BACKEND_HOST}:${BACKEND_PORT}/user`;

export {
    AUTH_BASE_URL,
    USER_BASE_URL
};