# The docker-compose version
version: '3'

# Define services of project
services:

  # Database container
  database:
    container_name: sitefodi-db
    image: 'mysql:5.7'
    ports:
      - 3306:3306
    env_file:
      - ../.env/mysql
      - ../.env/root_mysql
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
